### ISSUE TITLE
vimprocが使える時はvimprocを使って欲しい

### ISSUE THREAD

**Issue by Shougo** [yuratomo/w3m.vim#1]
こんにちは。Shougoといいます。

w3m.vimすごいですね。こちらの環境でもきちんと動くことを確認しました。
ただ、Windows環境においてリンクをたどるときにDos窓が出るのは私にとって若干気になります。
vimprocが使える環境では、system()の代わりにvimproc#system()を使用することで対処できますので、対応してもらえないでしょうか。

例：

```
function s:system(string)
  if exists('*vimproc#system()')
    return vimproc#system(a:string)
  else
    return system(a:string)
  endif
endfunction
```

追記： Windows XPでしか動作確認していないとのことですが、Windows 7 64bit環境+ w3m mingw binaryで動作しました。Linuxでも確認しておきます。

**Comment by Shougo** [comment]
ちなみに、vimprocでは2> /dev/nullか&> /dev/nullで標準エラー出力を消すことができます。つまりUNIXシェルに準拠しています。

**Comment by yuratomo** [comment]
こんにちは。yuratomoです。

了解しました。
アドバイスどもです。
vimscript最近よくかいていますが、
実はそんなに得意ではないので大変たすかります。
順次修正します。

## 

2012年3月18日11:14 Shougo
reply@reply.github.com:

**Comment by Shougo** [comment]
おお、ありがとうございます。
w3m.vimの今後に期待しています:-)

**Comment by yuratomo** [comment]
修正してみました。

**Comment by Shougo** [comment]
了解です。ちなみに、w3m.vimはLinux環境でも動作することを確認しました。
