### ISSUE TITLE
preview local webpage

### ISSUE THREAD

**Issue by tangfu** [yuratomo/w3m.vim#12]
Hi,yuratomo. The plugin is great, l love it. 

---

However I hope it can preview _local webpage_,not just webpage in the internat.
Basic usage is  "W3m url or keyword".
For example,  I type "W3m /home/tangfu/test.html",  it will be treated as a keword.

Please you can consider it. Thanks for the work you did again.

**Comment by yuratomo** [comment]
Hi tangfu.
I would like to add a search engine for local html file.
(But It will probably not work in mingw.)

usage is "W3m local /home/tangfu/test.html".

**Comment by yuratomo** [comment]
I added search engine for local html file.

[usage]
:W3m local /home/tangfu/test.html
or
:W3mLocal /home/tangfu/test.html

W3mLocal is same as "W3m local xxx".
but, It can be used file completion.

**Comment by tangfu** [comment]
hi yuratomo, it works.
greate changes, haha.

W3mLocal is enough to me, path completion is convenient.
Thanks !!!
