### ISSUE TITLE
autoload化してほしい

### ISSUE THREAD

**Issue by Shougo** [yuratomo/w3m.vim#2]
現在のw3m.vimはplugin/w3m.vimだけですが、今後のことを考えると肥大化することは確実で、
描画ルーチンをautoload/w3m.vimに分離したほうが良いと思います。
autoload化することにより、w3m.vimを使用しないときはw3m.vimは読み込まれず、Vimの起動時間短縮に貢献します。

もっというと、現在でも30kBくらいあるので、いくつかの.vimファイルに分割したほうが良いかもしれません。

**Comment by yuratomo** [comment]
とりあえず、autoload/w3m.vimとplugin/w3m.vimに分けてみました。
ファイルの細分化は必要がでてきたら対応します。

**Comment by Shougo** [comment]
ありがとうございます。それでいいと思います。
