### ISSUE TITLE
line   80: w3m is not exist!!  

### ISSUE THREAD

**Issue by baopham** [yuratomo/w3m.vim#8]
Keep getting this error: 
`Error detected while processing /Users/baopham/.vim/bundle/w3m/plugin/w3m.vim:
line   80:
w3m is not exist!!`

which I think it's trying to say w3m does not exist but why?

**Comment by yuratomo** [comment]
Do you use windows?
If you use windows, you can use cygwin or mingw w3m.exe.
You can download w3m.exe(mingw) from the following URL. 

```
http://www.daionet.gr.jp/~knok/software/misc/w3m-bin.exe
```

And through the path to the w3m.exe or define vimrc as follows.

```
let g:w3m#command = 'C:\hoge\w3m.exe'
```

**Comment by baopham** [comment]
No i use Mac, but i'll install a mac version. thanks
